### ISSUE TITLE
Use 2 separate createStore()'s?

### ISSUE THREAD

**Issue by daleyjem** [ilkeraltin/react-ssr-news#127]
I realize this is just an example project, but as anyone who might be using it as a boilerplate... might there be a more efficient way of using `createStore()` to consolidate it to one file?

I wanted to enable [redux devtools](https://github.com/zalmoxisus/redux-devtools-extension), and spent a lot of time editing the server-side version of `createStore()`, wondering why it wasn't working in the browser extension... later to find out there's a separate server and client usage of it.

For what it's worth... This has been the boilerplate for my project and it's been working great so far, so definitely kudos for that.

Lastly, if you've seen a good SSR React app boilerplate that you'd recommend for future projects, please feel free to offer some ideas on that.

**Comment by CharlyJazz** [comment]
NEXT JS DUDE

**Comment by ilkeraltin** [comment]
Yeap, you can give it a try to the Next
