### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by FazelMahdi** [ilkeraltin/react-ssr-news#138]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FazelMahdi** [comment]
hi ilkeraltin
how we should use assets folder in this project? after getting build of project, it wouldn't shown in build directory.

**Comment by ilkeraltin** [comment]
You need to extend/modify webpack settings to also build/minify/move assets.

**Comment by FazelMahdi** [comment]
does it fix the problem with importing static images in component?
