### ISSUE TITLE
A memory leak

### ISSUE THREAD

**Issue by mihanizm56** [ilkeraltin/react-ssr-news#57]
I have a memory leak when running your code by the comand 'npm run dev'
Steps to reproduce:
1) npm run dev
2) start the localhost url into the browser
3) couple of times tap ctrl+s
4) wait for 2-5 minutes and here we are((

**Comment by ilkeraltin** [comment]
@mihanizm56 I'll try to reproduce it. Thanks for the heads up!

**Comment by ilkeraltin** [comment]
@mihanizm56  I tried to reproduce it on Macbook Pro, but couldn't manage. It seems everything works fine. Please try to re-install the project and let me know if you need further help.
